# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: R

cache:
  packages: yes

sudo: required

warnings_are_errors: false

#   Subdirectories containing R packages to be compiled
env:
  - PACK_DIR=soiltexture

apt_packages:
  -  tk-dev
  
addons:
  apt:
    packages:
      - tcl8.5-dev
      - tk8.5-dev

before_install:
  - cd pkg/$PACK_DIR
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb star

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
 